#!/usr/bin/env python

import RPi.GPIO as GPIO
import time

# Use "logical" pin numbers
GPIO.setmode(GPIO.BCM)

# Disable "This channel is already in use" warnings
GPIO.setwarnings(False)

GPIO.setup(2, GPIO.OUT)
GPIO.setup(3, GPIO.OUT)

GPIO.output(2, False)
GPIO.output(3, False)

GPIO.setup(4, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(5, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

while True:

        if GPIO.input(4) == 1:
                GPIO.output(2, True)
                time.sleep(0.05)
                GPIO.output(2, False)
                time.sleep(0.05)
        if GPIO.input(5) == 1:
                GPIO.output(2, True)
                time.sleep(0.5)
                GPIO.output(2, False)
                time.sleep(0.5)
